points:
  key:
    padding: cy
    footprints:
        choc_hotswap:
          type: choc
          nets:
            from: =colrow
            to: =column_net
          params:
            keycaps: true
            reverse: true
            hotswap: true
        # Comment out this to remove the non-hotswap footprint
        choc:
          type: choc
          anchor:
            rotate: 180
          nets:
            from: =colrow
            to: =column_net
          params:
              keycaps: true
              reverse: true
        diode:
           type: diode
           anchor:
             #rotate: 90
             shift: [-3,-8.25]
             #shift: [0, -7.5]
           nets:
             from: =colrow
             to: =row_net
  zones: 
    matrix:
      anchor:
      columns:
        # pinkyOuter:
        #   stagger: 0  
        #   spread: cx
        #   rows:
        #     top:
        #       bind: [0,3,0,2]          
        #     home:
        #       bind: [0,3,2,2]
        #     bottom:
        #       bind: [0,3,2,2]
        #   key:
        #     column_net: P9
        pinky:
          stagger: 5
          spread: cx
          rotate: 8
          rows:
            top:
              bind: [0,4,0,2]          
            home:
            bottom:
              bind: [0,3,7,1]
          key:
            column_net: P8
        ring:
          stagger: 12
          spread: cx+1
          rotate: -4
          rows:
            top:
              bind: [0,4,0,2] 
            bottom:
              bind: [0,3,19,2]
          key:
            column_net: P7
        middle:
          stagger: 5
          spread: cx+1
          rotate: -4
          rows:
            top:
              bind: [0,5,0,2]
            home: 
              bind: [0,4,0,0] 
            bottom:
              bind: [0,5,24,0]
          key:
            column_net: P6
        index:
          stagger: -6
          spread: cx+1
          rotate: -4
          rows:
            top:
              bind: [2,0,0,-3]
            home:
              bind: [0,2,0,0]
            bottom: 
              bind: [0,2,0,0]
          key:
            column_net: P5
        inner:
          stagger: -2
          spread: cx
          rows:
            top:
              bind: [0,2,0,3]
            home:
              bind: [8,25,0,0]
            bottom: 
              bind: [0,25,7,0]
          key:
            column_net: P4
      rows:
        bottom:
          bind: [0,0,0,0]
          row_net: P3
        home:
          bind: [0,3,0,0]
          row_net: P2
        top:
          bind: [0,3,0,0]
          row_net: P0
    thumbfan:
      anchor:
        ref: matrix_inner_bottom
        shift: [-cx-10, -cx-5]
      columns:
        near:
          rotate: -18
          spread: cx+1.5
          rows:
            thumb:
              bind: [8,4,0,19]
          key:
            column_net: P16
        far: 
          spread: cx
          rotate: -11
          origin: [-10, -10]
          rows:
            thumb:
              bind: [14,0.7,0,5]
          key:
            column_net: P14
      rows:
        thumb:
          row_net: P10
    # Uncomment this part if you only want 2 outer pinkey keys
    # also comment out the first column in the main matrix
    pinkyOuter:
      anchor:
        ref: matrix_pinky_top
        shift: [-cx-1.2, -cx-10]
        rotate: 2
      columns:
        reachPinkey:
          key:
            column_net: P9
          rows:
            top:
              bind: [0,2.5,0,1]
              colrow: P0       
            home:
              bind: [0,2.5,0,1]
              colrow: P3
      rows:
        home:
          bind: [0,3,0,0]
          row_net: P3
        top:
          bind: [0,3,0,0]
          row_net: P0
outlines:
  exports:
    raw: 
      - type: keys
        side: left
        size: [1cx - 0.5 , 1cx -0.5]
    cutout:
      - type: outline
        name: raw
        fillet: 1.7
    keycap_outlines:
      - type: keys
        side: left
        size: [1cx - 0.5, 1cy - 0.5] # Choc keycaps are 17.5 x 16.5
        bound: false
    preview:
        [keycap_outlines]
pcbs:
  hopperv2:
    outlines:
      matrix:
        outline: cutout
      keycaps:
        outline: preview
        layer: Eco1.User
    footprints:
      promicro:
        type: promicro_pretty
        anchor:
          ref: matrix_inner_home
          shift: [22, -2]
          rotate: -90
      trrs:
        type: trrs
        anchor:
          ref: matrix_inner_bottom
          shift: [34,-13]
          rotate: -90
        nets:
          A: GND
          B: GND
          C: P2
          D: VCC
        params:
          reverse: true
          symmetric: true
      pcm12:
        type: pcm12
        anchor:
          ref: thumbfan_far_thumb
          shift: [6, 15]
          rotate: 90
        nets:
          from: pos  
          to: RAW
        params:
          reverse: true 
      b3u1000p:
        type: b3u1000p
        nets:
          r1: RST  
          r2: GND
        anchor:
          ref: matrix_inner_bottom
          shift: [0,-12]
          rotate: 180
        params:
          reverse: true 
      bat:
        type: bat
        nets: 
          neg: GND
        anchor:
          ref: matrix_inner_bottom
          shift: [22,-3]
          rotate: 90
      via1:
        type: via
        anchor: 
          ref: thumbfan_far_thumb
          shift: [1, 15]
        nets: 
          net: RAW 
      via2:
        type: via
        anchor: 
          ref: thumbfan_far_thumb
          shift: [1, 13]
        nets: 
          net: pos 
      via3:
        type: via
        anchor: 
          ref: matrix_inner_bottom
          shift: [7,-12]
        nets: 
          net: GND 
      via4:
        type: via
        anchor: 
          ref: thumbfan_far_thumb
          shift: [0,10]
        nets: 
          net: RST